"""Generated by hayate-sql. Do not edit by hand."""

from typing import TypedDict, cast

from hayate_sql import (
    Cardinality,
    Column,
    CommandResult,
    Database,
    Parameter,
    Query,
)


class CloseTaskRow(TypedDict):
    id: int


CLOSE_TASK_QUERY = Query(
    name="close_task",
    sql=("UPDATE task\nSET status = 'closed'\nWHERE tenant_key = ?1\n  AND id = ?2\nRETURNING id"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("id", "int"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def close_task(
    db: Database,
    /,
    *,
    tenant_key: str,
    id: int,
) -> CloseTaskRow | None:
    return cast(
        "CloseTaskRow | None",
        await db.run(
            CLOSE_TASK_QUERY,
            tenant_key=tenant_key,
            id=id,
        ),
    )


class CountAdminAuditEventsForObjectRow(TypedDict):
    total: int


COUNT_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY = Query(
    name="count_admin_audit_events_for_object",
    sql=(
        "SELECT count(*) AS total\n"
        "FROM admin_audit_event\n"
        "WHERE resource = ?1\n"
        "  AND object_id = ?2"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("resource", "str"),
        Parameter("object_id", "str"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_admin_audit_events_for_object(
    db: Database,
    /,
    *,
    resource: str,
    object_id: str,
) -> CountAdminAuditEventsForObjectRow:
    return cast(
        "CountAdminAuditEventsForObjectRow",
        await db.run(
            COUNT_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY,
            resource=resource,
            object_id=object_id,
        ),
    )


class CountTaskRelationshipChoicesRow(TypedDict):
    total: int


COUNT_TASK_RELATIONSHIP_CHOICES_QUERY = Query(
    name="count_task_relationship_choices",
    sql=(
        "SELECT count(*) AS total\n"
        "FROM task\n"
        "WHERE tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(name), lower(?2)) > 0)\n"
        "  AND (?3 IS NULL OR id <> ?3)"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("exclude_id", "int?"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_task_relationship_choices(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    exclude_id: int | None,
) -> CountTaskRelationshipChoicesRow:
    return cast(
        "CountTaskRelationshipChoicesRow",
        await db.run(
            COUNT_TASK_RELATIONSHIP_CHOICES_QUERY,
            tenant_key=tenant_key,
            search=search,
            exclude_id=exclude_id,
        ),
    )


class CountTasksRow(TypedDict):
    total: int


COUNT_TASKS_QUERY = Query(
    name="count_tasks",
    sql=(
        "SELECT count(*) AS total\n"
        "FROM task\n"
        "WHERE tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(name), lower(?2)) > 0)\n"
        "  AND (?3 = '' OR status = ?3)"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("status", "str"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_tasks(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    status: str,
) -> CountTasksRow:
    return cast(
        "CountTasksRow",
        await db.run(
            COUNT_TASKS_QUERY,
            tenant_key=tenant_key,
            search=search,
            status=status,
        ),
    )


CREATE_ADMIN_AUDIT_EVENT_QUERY = Query(
    name="create_admin_audit_event",
    sql=(
        "INSERT INTO admin_audit_event (\n"
        "    occurred_at,\n"
        "    phase,\n"
        "    action,\n"
        "    operation,\n"
        "    resource,\n"
        "    object_id,\n"
        "    actor_id,\n"
        "    error_type\n"
        ")\n"
        "VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)"
    ),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("occurred_at", "str"),
        Parameter("phase", "str"),
        Parameter("action", "str"),
        Parameter("operation", "str?"),
        Parameter("resource", "str"),
        Parameter("object_id", "str?"),
        Parameter("actor_id", "str?"),
        Parameter("error_type", "str?"),
    ),
    columns=(),
    timeout_ms=None,
)


async def create_admin_audit_event(
    db: Database,
    /,
    *,
    occurred_at: str,
    phase: str,
    action: str,
    operation: str | None,
    resource: str,
    object_id: str | None,
    actor_id: str | None,
    error_type: str | None,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            CREATE_ADMIN_AUDIT_EVENT_QUERY,
            occurred_at=occurred_at,
            phase=phase,
            action=action,
            operation=operation,
            resource=resource,
            object_id=object_id,
            actor_id=actor_id,
            error_type=error_type,
        ),
    )


class CreateSubtaskRow(TypedDict):
    id: int


CREATE_SUBTASK_QUERY = Query(
    name="create_subtask",
    sql=(
        "INSERT INTO task (tenant_key, name, status, active, notes, parent_id)\n"
        "SELECT ?1, ?3, ?4, ?5, ?6, parent.id\n"
        "FROM task AS parent\n"
        "WHERE parent.tenant_key = ?1\n"
        "  AND parent.id = ?2\n"
        "RETURNING id"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("parent_id", "int"),
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def create_subtask(
    db: Database,
    /,
    *,
    tenant_key: str,
    parent_id: int,
    name: str,
    status: str,
    active: bool,
    notes: str,
) -> CreateSubtaskRow | None:
    return cast(
        "CreateSubtaskRow | None",
        await db.run(
            CREATE_SUBTASK_QUERY,
            tenant_key=tenant_key,
            parent_id=parent_id,
            name=name,
            status=status,
            active=active,
            notes=notes,
        ),
    )


class CreateTaskRow(TypedDict):
    id: int


CREATE_TASK_QUERY = Query(
    name="create_task",
    sql=(
        "INSERT INTO task (tenant_key, name, status, active, notes, parent_id)\n"
        "SELECT ?1, ?2, ?3, ?4, ?5, parent.id\n"
        "FROM (SELECT 1) AS one\n"
        "LEFT JOIN task AS parent\n"
        "  ON parent.tenant_key = ?1\n"
        " AND parent.id = ?6\n"
        "WHERE ?6 IS NULL OR parent.id IS NOT NULL\n"
        "RETURNING id"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
        Parameter("parent_id", "int?"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def create_task(
    db: Database,
    /,
    *,
    tenant_key: str,
    name: str,
    status: str,
    active: bool,
    notes: str,
    parent_id: int | None,
) -> CreateTaskRow | None:
    return cast(
        "CreateTaskRow | None",
        await db.run(
            CREATE_TASK_QUERY,
            tenant_key=tenant_key,
            name=name,
            status=status,
            active=active,
            notes=notes,
            parent_id=parent_id,
        ),
    )


class DeleteSubtaskRow(TypedDict):
    id: int


DELETE_SUBTASK_QUERY = Query(
    name="delete_subtask",
    sql=(
        "DELETE FROM task\nWHERE tenant_key = ?1\n  AND parent_id = ?2\n  AND id = ?3\nRETURNING id"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("parent_id", "int"),
        Parameter("id", "int"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def delete_subtask(
    db: Database,
    /,
    *,
    tenant_key: str,
    parent_id: int,
    id: int,
) -> DeleteSubtaskRow | None:
    return cast(
        "DeleteSubtaskRow | None",
        await db.run(
            DELETE_SUBTASK_QUERY,
            tenant_key=tenant_key,
            parent_id=parent_id,
            id=id,
        ),
    )


class DeleteTaskRow(TypedDict):
    id: int


DELETE_TASK_QUERY = Query(
    name="delete_task",
    sql=("DELETE FROM task\nWHERE tenant_key = ?1\n  AND id = ?2\nRETURNING id"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("id", "int"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def delete_task(
    db: Database,
    /,
    *,
    tenant_key: str,
    id: int,
) -> DeleteTaskRow | None:
    return cast(
        "DeleteTaskRow | None",
        await db.run(
            DELETE_TASK_QUERY,
            tenant_key=tenant_key,
            id=id,
        ),
    )


class GetAdminRoleRow(TypedDict):
    role: str
    tenant_key: str


GET_ADMIN_ROLE_QUERY = Query(
    name="get_admin_role",
    sql=("SELECT role, tenant_key\nFROM admin_role\nWHERE user_id = ?1"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(Parameter("user_id", "str"),),
    columns=(
        Column("role", "str"),
        Column("tenant_key", "str"),
    ),
    timeout_ms=None,
)


async def get_admin_role(
    db: Database,
    /,
    *,
    user_id: str,
) -> GetAdminRoleRow | None:
    return cast(
        "GetAdminRoleRow | None",
        await db.run(
            GET_ADMIN_ROLE_QUERY,
            user_id=user_id,
        ),
    )


class GetTaskRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str
    parent_id: int | None
    parent_name: str | None


GET_TASK_QUERY = Query(
    name="get_task",
    sql=(
        "SELECT child.id, child.name, child.status, child.active, child.notes,\n"
        "       child.parent_id, parent.name AS parent_name\n"
        "FROM task AS child\n"
        "LEFT JOIN task AS parent\n"
        "  ON parent.id = child.parent_id\n"
        " AND parent.tenant_key = child.tenant_key\n"
        "WHERE child.tenant_key = ?1\n"
        "  AND child.id = ?2"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("id", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
        Column("parent_id", "int?"),
        Column("parent_name", "str?"),
    ),
    timeout_ms=None,
)


async def get_task(
    db: Database,
    /,
    *,
    tenant_key: str,
    id: int,
) -> GetTaskRow | None:
    return cast(
        "GetTaskRow | None",
        await db.run(
            GET_TASK_QUERY,
            tenant_key=tenant_key,
            id=id,
        ),
    )


class GetTaskRelationshipChoiceRow(TypedDict):
    id: int
    name: str


GET_TASK_RELATIONSHIP_CHOICE_QUERY = Query(
    name="get_task_relationship_choice",
    sql=(
        "SELECT id, name\n"
        "FROM task\n"
        "WHERE tenant_key = ?1\n"
        "  AND id = ?2\n"
        "  AND (?3 IS NULL OR id <> ?3)"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("id", "int"),
        Parameter("exclude_id", "int?"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
    ),
    timeout_ms=None,
)


async def get_task_relationship_choice(
    db: Database,
    /,
    *,
    tenant_key: str,
    id: int,
    exclude_id: int | None,
) -> GetTaskRelationshipChoiceRow | None:
    return cast(
        "GetTaskRelationshipChoiceRow | None",
        await db.run(
            GET_TASK_RELATIONSHIP_CHOICE_QUERY,
            tenant_key=tenant_key,
            id=id,
            exclude_id=exclude_id,
        ),
    )


class ListAdminAuditEventsRow(TypedDict):
    id: int
    occurred_at: str
    phase: str
    action: str
    operation: str | None
    resource: str
    object_id: str | None
    actor_id: str | None
    error_type: str | None


LIST_ADMIN_AUDIT_EVENTS_QUERY = Query(
    name="list_admin_audit_events",
    sql=(
        "SELECT id, occurred_at, phase, action, operation,\n"
        "       resource, object_id, actor_id, error_type\n"
        "FROM admin_audit_event\n"
        "ORDER BY id"
    ),
    cardinality=Cardinality.MANY,
    parameters=(),
    columns=(
        Column("id", "int"),
        Column("occurred_at", "str"),
        Column("phase", "str"),
        Column("action", "str"),
        Column("operation", "str?"),
        Column("resource", "str"),
        Column("object_id", "str?"),
        Column("actor_id", "str?"),
        Column("error_type", "str?"),
    ),
    timeout_ms=None,
)


async def list_admin_audit_events(db: Database, /) -> list[ListAdminAuditEventsRow]:
    return cast(
        "list[ListAdminAuditEventsRow]",
        await db.run(LIST_ADMIN_AUDIT_EVENTS_QUERY),
    )


class ListAdminAuditEventsForObjectRow(TypedDict):
    occurred_at: str
    phase: str
    action: str
    operation: str | None
    resource: str
    object_id: str | None
    actor_id: str | None
    error_type: str | None


LIST_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY = Query(
    name="list_admin_audit_events_for_object",
    sql=(
        "SELECT occurred_at, phase, action, operation,\n"
        "       resource, object_id, actor_id, error_type\n"
        "FROM admin_audit_event\n"
        "WHERE resource = ?1\n"
        "  AND object_id = ?2\n"
        "ORDER BY id DESC\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("resource", "str"),
        Parameter("object_id", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("occurred_at", "str"),
        Column("phase", "str"),
        Column("action", "str"),
        Column("operation", "str?"),
        Column("resource", "str"),
        Column("object_id", "str?"),
        Column("actor_id", "str?"),
        Column("error_type", "str?"),
    ),
    timeout_ms=None,
)


async def list_admin_audit_events_for_object(
    db: Database,
    /,
    *,
    resource: str,
    object_id: str,
    limit: int,
    offset: int,
) -> list[ListAdminAuditEventsForObjectRow]:
    return cast(
        "list[ListAdminAuditEventsForObjectRow]",
        await db.run(
            LIST_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY,
            resource=resource,
            object_id=object_id,
            limit=limit,
            offset=offset,
        ),
    )


class ListSubtasksRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str
    parent_id: int | None
    parent_name: str | None


LIST_SUBTASKS_QUERY = Query(
    name="list_subtasks",
    sql=(
        "SELECT child.id, child.name, child.status, child.active, child.notes,\n"
        "       child.parent_id, parent.name AS parent_name\n"
        "FROM task AS child\n"
        "JOIN task AS parent\n"
        "  ON parent.id = child.parent_id\n"
        " AND parent.tenant_key = child.tenant_key\n"
        "WHERE child.tenant_key = ?1\n"
        "  AND child.parent_id = ?2\n"
        "ORDER BY child.id\n"
        "LIMIT ?3"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("parent_id", "int"),
        Parameter("limit", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
        Column("parent_id", "int?"),
        Column("parent_name", "str?"),
    ),
    timeout_ms=None,
)


async def list_subtasks(
    db: Database,
    /,
    *,
    tenant_key: str,
    parent_id: int,
    limit: int,
) -> list[ListSubtasksRow]:
    return cast(
        "list[ListSubtasksRow]",
        await db.run(
            LIST_SUBTASKS_QUERY,
            tenant_key=tenant_key,
            parent_id=parent_id,
            limit=limit,
        ),
    )


class ListTaskRelationshipChoicesRow(TypedDict):
    id: int
    name: str


LIST_TASK_RELATIONSHIP_CHOICES_QUERY = Query(
    name="list_task_relationship_choices",
    sql=(
        "SELECT id, name\n"
        "FROM task\n"
        "WHERE tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(name), lower(?2)) > 0)\n"
        "  AND (?3 IS NULL OR id <> ?3)\n"
        "ORDER BY name, id\n"
        "LIMIT ?4 OFFSET ?5"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("exclude_id", "int?"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
    ),
    timeout_ms=None,
)


async def list_task_relationship_choices(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    exclude_id: int | None,
    limit: int,
    offset: int,
) -> list[ListTaskRelationshipChoicesRow]:
    return cast(
        "list[ListTaskRelationshipChoicesRow]",
        await db.run(
            LIST_TASK_RELATIONSHIP_CHOICES_QUERY,
            tenant_key=tenant_key,
            search=search,
            exclude_id=exclude_id,
            limit=limit,
            offset=offset,
        ),
    )


class ListTasksDefaultRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str
    parent_id: int | None
    parent_name: str | None


LIST_TASKS_DEFAULT_QUERY = Query(
    name="list_tasks_default",
    sql=(
        "SELECT child.id, child.name, child.status, child.active, child.notes,\n"
        "       child.parent_id, parent.name AS parent_name\n"
        "FROM task AS child\n"
        "LEFT JOIN task AS parent\n"
        "  ON parent.id = child.parent_id\n"
        " AND parent.tenant_key = child.tenant_key\n"
        "WHERE child.tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(child.name), lower(?2)) > 0)\n"
        "  AND (?3 = '' OR child.status = ?3)\n"
        "ORDER BY child.id\n"
        "LIMIT ?4 OFFSET ?5"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
        Column("parent_id", "int?"),
        Column("parent_name", "str?"),
    ),
    timeout_ms=None,
)


async def list_tasks_default(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksDefaultRow]:
    return cast(
        "list[ListTasksDefaultRow]",
        await db.run(
            LIST_TASKS_DEFAULT_QUERY,
            tenant_key=tenant_key,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class ListTasksNameAscRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str
    parent_id: int | None
    parent_name: str | None


LIST_TASKS_NAME_ASC_QUERY = Query(
    name="list_tasks_name_asc",
    sql=(
        "SELECT child.id, child.name, child.status, child.active, child.notes,\n"
        "       child.parent_id, parent.name AS parent_name\n"
        "FROM task AS child\n"
        "LEFT JOIN task AS parent\n"
        "  ON parent.id = child.parent_id\n"
        " AND parent.tenant_key = child.tenant_key\n"
        "WHERE child.tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(child.name), lower(?2)) > 0)\n"
        "  AND (?3 = '' OR child.status = ?3)\n"
        "ORDER BY child.name, child.id\n"
        "LIMIT ?4 OFFSET ?5"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
        Column("parent_id", "int?"),
        Column("parent_name", "str?"),
    ),
    timeout_ms=None,
)


async def list_tasks_name_asc(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksNameAscRow]:
    return cast(
        "list[ListTasksNameAscRow]",
        await db.run(
            LIST_TASKS_NAME_ASC_QUERY,
            tenant_key=tenant_key,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class ListTasksNameDescRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str
    parent_id: int | None
    parent_name: str | None


LIST_TASKS_NAME_DESC_QUERY = Query(
    name="list_tasks_name_desc",
    sql=(
        "SELECT child.id, child.name, child.status, child.active, child.notes,\n"
        "       child.parent_id, parent.name AS parent_name\n"
        "FROM task AS child\n"
        "LEFT JOIN task AS parent\n"
        "  ON parent.id = child.parent_id\n"
        " AND parent.tenant_key = child.tenant_key\n"
        "WHERE child.tenant_key = ?1\n"
        "  AND (?2 = '' OR instr(lower(child.name), lower(?2)) > 0)\n"
        "  AND (?3 = '' OR child.status = ?3)\n"
        "ORDER BY child.name DESC, child.id DESC\n"
        "LIMIT ?4 OFFSET ?5"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
        Column("parent_id", "int?"),
        Column("parent_name", "str?"),
    ),
    timeout_ms=None,
)


async def list_tasks_name_desc(
    db: Database,
    /,
    *,
    tenant_key: str,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksNameDescRow]:
    return cast(
        "list[ListTasksNameDescRow]",
        await db.run(
            LIST_TASKS_NAME_DESC_QUERY,
            tenant_key=tenant_key,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class UpdateSubtaskRow(TypedDict):
    id: int


UPDATE_SUBTASK_QUERY = Query(
    name="update_subtask",
    sql=(
        "UPDATE task\n"
        "SET name = ?4,\n"
        "    status = ?5,\n"
        "    active = ?6,\n"
        "    notes = ?7\n"
        "WHERE tenant_key = ?1\n"
        "  AND parent_id = ?2\n"
        "  AND id = ?3\n"
        "RETURNING id"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("parent_id", "int"),
        Parameter("id", "int"),
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def update_subtask(
    db: Database,
    /,
    *,
    tenant_key: str,
    parent_id: int,
    id: int,
    name: str,
    status: str,
    active: bool,
    notes: str,
) -> UpdateSubtaskRow | None:
    return cast(
        "UpdateSubtaskRow | None",
        await db.run(
            UPDATE_SUBTASK_QUERY,
            tenant_key=tenant_key,
            parent_id=parent_id,
            id=id,
            name=name,
            status=status,
            active=active,
            notes=notes,
        ),
    )


class UpdateTaskRow(TypedDict):
    id: int


UPDATE_TASK_QUERY = Query(
    name="update_task",
    sql=(
        "UPDATE task\n"
        "SET name = ?3,\n"
        "    status = ?4,\n"
        "    active = ?5,\n"
        "    notes = ?6,\n"
        "    parent_id = ?7\n"
        "WHERE tenant_key = ?1\n"
        "  AND id = ?2\n"
        "  AND (?7 IS NULL OR ?7 <> ?2)\n"
        "  AND (\n"
        "    ?7 IS NULL\n"
        "    OR EXISTS (\n"
        "      SELECT 1\n"
        "      FROM task AS parent\n"
        "      WHERE parent.tenant_key = ?1\n"
        "        AND parent.id = ?7\n"
        "    )\n"
        "  )\n"
        "RETURNING id"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("tenant_key", "str"),
        Parameter("id", "int"),
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
        Parameter("parent_id", "int?"),
    ),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def update_task(
    db: Database,
    /,
    *,
    tenant_key: str,
    id: int,
    name: str,
    status: str,
    active: bool,
    notes: str,
    parent_id: int | None,
) -> UpdateTaskRow | None:
    return cast(
        "UpdateTaskRow | None",
        await db.run(
            UPDATE_TASK_QUERY,
            tenant_key=tenant_key,
            id=id,
            name=name,
            status=status,
            active=active,
            notes=notes,
            parent_id=parent_id,
        ),
    )


UPSERT_ADMIN_ROLE_QUERY = Query(
    name="upsert_admin_role",
    sql=(
        "INSERT INTO admin_role (user_id, role, tenant_key)\n"
        "VALUES (?1, ?2, ?3)\n"
        "ON CONFLICT (user_id) DO UPDATE SET\n"
        "    role = excluded.role,\n"
        "    tenant_key = excluded.tenant_key"
    ),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("user_id", "str"),
        Parameter("role", "str"),
        Parameter("tenant_key", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def upsert_admin_role(
    db: Database,
    /,
    *,
    user_id: str,
    role: str,
    tenant_key: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            UPSERT_ADMIN_ROLE_QUERY,
            user_id=user_id,
            role=role,
            tenant_key=tenant_key,
        ),
    )


__all__ = [
    "CLOSE_TASK_QUERY",
    "COUNT_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY",
    "COUNT_TASKS_QUERY",
    "COUNT_TASK_RELATIONSHIP_CHOICES_QUERY",
    "CREATE_ADMIN_AUDIT_EVENT_QUERY",
    "CREATE_SUBTASK_QUERY",
    "CREATE_TASK_QUERY",
    "DELETE_SUBTASK_QUERY",
    "DELETE_TASK_QUERY",
    "GET_ADMIN_ROLE_QUERY",
    "GET_TASK_QUERY",
    "GET_TASK_RELATIONSHIP_CHOICE_QUERY",
    "LIST_ADMIN_AUDIT_EVENTS_FOR_OBJECT_QUERY",
    "LIST_ADMIN_AUDIT_EVENTS_QUERY",
    "LIST_SUBTASKS_QUERY",
    "LIST_TASKS_DEFAULT_QUERY",
    "LIST_TASKS_NAME_ASC_QUERY",
    "LIST_TASKS_NAME_DESC_QUERY",
    "LIST_TASK_RELATIONSHIP_CHOICES_QUERY",
    "UPDATE_SUBTASK_QUERY",
    "UPDATE_TASK_QUERY",
    "UPSERT_ADMIN_ROLE_QUERY",
    "CloseTaskRow",
    "CountAdminAuditEventsForObjectRow",
    "CountTaskRelationshipChoicesRow",
    "CountTasksRow",
    "CreateSubtaskRow",
    "CreateTaskRow",
    "DeleteSubtaskRow",
    "DeleteTaskRow",
    "GetAdminRoleRow",
    "GetTaskRelationshipChoiceRow",
    "GetTaskRow",
    "ListAdminAuditEventsForObjectRow",
    "ListAdminAuditEventsRow",
    "ListSubtasksRow",
    "ListTaskRelationshipChoicesRow",
    "ListTasksDefaultRow",
    "ListTasksNameAscRow",
    "ListTasksNameDescRow",
    "UpdateSubtaskRow",
    "UpdateTaskRow",
    "close_task",
    "count_admin_audit_events_for_object",
    "count_task_relationship_choices",
    "count_tasks",
    "create_admin_audit_event",
    "create_subtask",
    "create_task",
    "delete_subtask",
    "delete_task",
    "get_admin_role",
    "get_task",
    "get_task_relationship_choice",
    "list_admin_audit_events",
    "list_admin_audit_events_for_object",
    "list_subtasks",
    "list_task_relationship_choices",
    "list_tasks_default",
    "list_tasks_name_asc",
    "list_tasks_name_desc",
    "update_subtask",
    "update_task",
    "upsert_admin_role",
]
