"""Generated by hayate-sql. Do not edit by hand."""

from typing import TypedDict, cast

from hayate_sql import (
    Cardinality,
    Column,
    CommandResult,
    Database,
    Parameter,
    Query,
)


class CountTasksRow(TypedDict):
    total: int


COUNT_TASKS_QUERY = Query(
    name="count_tasks",
    sql=(
        "SELECT count(*) AS total\n"
        "FROM task\n"
        "WHERE (?1 = '' OR instr(lower(name), lower(?1)) > 0)\n"
        "  AND (?2 = '' OR status = ?2)"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("search", "str"),
        Parameter("status", "str"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_tasks(
    db: Database,
    /,
    *,
    search: str,
    status: str,
) -> CountTasksRow:
    return cast(
        "CountTasksRow",
        await db.run(
            COUNT_TASKS_QUERY,
            search=search,
            status=status,
        ),
    )


CREATE_ADMIN_AUDIT_EVENT_QUERY = Query(
    name="create_admin_audit_event",
    sql=(
        "INSERT INTO admin_audit_event (\n"
        "    occurred_at,\n"
        "    phase,\n"
        "    action,\n"
        "    resource,\n"
        "    object_id,\n"
        "    actor_id,\n"
        "    error_type\n"
        ")\n"
        "VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)"
    ),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("occurred_at", "str"),
        Parameter("phase", "str"),
        Parameter("action", "str"),
        Parameter("resource", "str"),
        Parameter("object_id", "str?"),
        Parameter("actor_id", "str?"),
        Parameter("error_type", "str?"),
    ),
    columns=(),
    timeout_ms=None,
)


async def create_admin_audit_event(
    db: Database,
    /,
    *,
    occurred_at: str,
    phase: str,
    action: str,
    resource: str,
    object_id: str | None,
    actor_id: str | None,
    error_type: str | None,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            CREATE_ADMIN_AUDIT_EVENT_QUERY,
            occurred_at=occurred_at,
            phase=phase,
            action=action,
            resource=resource,
            object_id=object_id,
            actor_id=actor_id,
            error_type=error_type,
        ),
    )


class CreateTaskRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


CREATE_TASK_QUERY = Query(
    name="create_task",
    sql=(
        "INSERT INTO task (name, status, active, notes)\n"
        "VALUES (?1, ?2, ?3, ?4)\n"
        "RETURNING id, name, status, active, notes"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def create_task(
    db: Database,
    /,
    *,
    name: str,
    status: str,
    active: bool,
    notes: str,
) -> CreateTaskRow:
    return cast(
        "CreateTaskRow",
        await db.run(
            CREATE_TASK_QUERY,
            name=name,
            status=status,
            active=active,
            notes=notes,
        ),
    )


class DeleteTaskRow(TypedDict):
    id: int


DELETE_TASK_QUERY = Query(
    name="delete_task",
    sql=("DELETE FROM task\nWHERE id = ?1\nRETURNING id"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(Parameter("id", "int"),),
    columns=(Column("id", "int"),),
    timeout_ms=None,
)


async def delete_task(
    db: Database,
    /,
    *,
    id: int,
) -> DeleteTaskRow | None:
    return cast(
        "DeleteTaskRow | None",
        await db.run(
            DELETE_TASK_QUERY,
            id=id,
        ),
    )


class GetAdminRoleRow(TypedDict):
    role: str


GET_ADMIN_ROLE_QUERY = Query(
    name="get_admin_role",
    sql=("SELECT role\nFROM admin_role\nWHERE user_id = ?1"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(Parameter("user_id", "str"),),
    columns=(Column("role", "str"),),
    timeout_ms=None,
)


async def get_admin_role(
    db: Database,
    /,
    *,
    user_id: str,
) -> GetAdminRoleRow | None:
    return cast(
        "GetAdminRoleRow | None",
        await db.run(
            GET_ADMIN_ROLE_QUERY,
            user_id=user_id,
        ),
    )


class GetTaskRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


GET_TASK_QUERY = Query(
    name="get_task",
    sql=("SELECT id, name, status, active, notes\nFROM task\nWHERE id = ?1"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(Parameter("id", "int"),),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def get_task(
    db: Database,
    /,
    *,
    id: int,
) -> GetTaskRow | None:
    return cast(
        "GetTaskRow | None",
        await db.run(
            GET_TASK_QUERY,
            id=id,
        ),
    )


class ListAdminAuditEventsRow(TypedDict):
    id: int
    occurred_at: str
    phase: str
    action: str
    resource: str
    object_id: str | None
    actor_id: str | None
    error_type: str | None


LIST_ADMIN_AUDIT_EVENTS_QUERY = Query(
    name="list_admin_audit_events",
    sql=(
        "SELECT id, occurred_at, phase, action, resource, object_id, actor_id, error_type\n"
        "FROM admin_audit_event\n"
        "ORDER BY id"
    ),
    cardinality=Cardinality.MANY,
    parameters=(),
    columns=(
        Column("id", "int"),
        Column("occurred_at", "str"),
        Column("phase", "str"),
        Column("action", "str"),
        Column("resource", "str"),
        Column("object_id", "str?"),
        Column("actor_id", "str?"),
        Column("error_type", "str?"),
    ),
    timeout_ms=None,
)


async def list_admin_audit_events(db: Database, /) -> list[ListAdminAuditEventsRow]:
    return cast(
        "list[ListAdminAuditEventsRow]",
        await db.run(LIST_ADMIN_AUDIT_EVENTS_QUERY),
    )


class ListTasksDefaultRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


LIST_TASKS_DEFAULT_QUERY = Query(
    name="list_tasks_default",
    sql=(
        "SELECT id, name, status, active, notes\n"
        "FROM task\n"
        "WHERE (?1 = '' OR instr(lower(name), lower(?1)) > 0)\n"
        "  AND (?2 = '' OR status = ?2)\n"
        "ORDER BY id\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def list_tasks_default(
    db: Database,
    /,
    *,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksDefaultRow]:
    return cast(
        "list[ListTasksDefaultRow]",
        await db.run(
            LIST_TASKS_DEFAULT_QUERY,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class ListTasksNameAscRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


LIST_TASKS_NAME_ASC_QUERY = Query(
    name="list_tasks_name_asc",
    sql=(
        "SELECT id, name, status, active, notes\n"
        "FROM task\n"
        "WHERE (?1 = '' OR instr(lower(name), lower(?1)) > 0)\n"
        "  AND (?2 = '' OR status = ?2)\n"
        "ORDER BY name, id\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def list_tasks_name_asc(
    db: Database,
    /,
    *,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksNameAscRow]:
    return cast(
        "list[ListTasksNameAscRow]",
        await db.run(
            LIST_TASKS_NAME_ASC_QUERY,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class ListTasksNameDescRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


LIST_TASKS_NAME_DESC_QUERY = Query(
    name="list_tasks_name_desc",
    sql=(
        "SELECT id, name, status, active, notes\n"
        "FROM task\n"
        "WHERE (?1 = '' OR instr(lower(name), lower(?1)) > 0)\n"
        "  AND (?2 = '' OR status = ?2)\n"
        "ORDER BY name DESC, id DESC\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("search", "str"),
        Parameter("status", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def list_tasks_name_desc(
    db: Database,
    /,
    *,
    search: str,
    status: str,
    limit: int,
    offset: int,
) -> list[ListTasksNameDescRow]:
    return cast(
        "list[ListTasksNameDescRow]",
        await db.run(
            LIST_TASKS_NAME_DESC_QUERY,
            search=search,
            status=status,
            limit=limit,
            offset=offset,
        ),
    )


class UpdateTaskRow(TypedDict):
    id: int
    name: str
    status: str
    active: int
    notes: str


UPDATE_TASK_QUERY = Query(
    name="update_task",
    sql=(
        "UPDATE task\n"
        "SET name = ?2,\n"
        "    status = ?3,\n"
        "    active = ?4,\n"
        "    notes = ?5\n"
        "WHERE id = ?1\n"
        "RETURNING id, name, status, active, notes"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("id", "int"),
        Parameter("name", "str"),
        Parameter("status", "str"),
        Parameter("active", "bool"),
        Parameter("notes", "str"),
    ),
    columns=(
        Column("id", "int"),
        Column("name", "str"),
        Column("status", "str"),
        Column("active", "int"),
        Column("notes", "str"),
    ),
    timeout_ms=None,
)


async def update_task(
    db: Database,
    /,
    *,
    id: int,
    name: str,
    status: str,
    active: bool,
    notes: str,
) -> UpdateTaskRow | None:
    return cast(
        "UpdateTaskRow | None",
        await db.run(
            UPDATE_TASK_QUERY,
            id=id,
            name=name,
            status=status,
            active=active,
            notes=notes,
        ),
    )


UPSERT_ADMIN_ROLE_QUERY = Query(
    name="upsert_admin_role",
    sql=(
        "INSERT INTO admin_role (user_id, role)\n"
        "VALUES (?1, ?2)\n"
        "ON CONFLICT (user_id) DO UPDATE SET role = excluded.role"
    ),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("user_id", "str"),
        Parameter("role", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def upsert_admin_role(
    db: Database,
    /,
    *,
    user_id: str,
    role: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            UPSERT_ADMIN_ROLE_QUERY,
            user_id=user_id,
            role=role,
        ),
    )


__all__ = [
    "COUNT_TASKS_QUERY",
    "CREATE_ADMIN_AUDIT_EVENT_QUERY",
    "CREATE_TASK_QUERY",
    "DELETE_TASK_QUERY",
    "GET_ADMIN_ROLE_QUERY",
    "GET_TASK_QUERY",
    "LIST_ADMIN_AUDIT_EVENTS_QUERY",
    "LIST_TASKS_DEFAULT_QUERY",
    "LIST_TASKS_NAME_ASC_QUERY",
    "LIST_TASKS_NAME_DESC_QUERY",
    "UPDATE_TASK_QUERY",
    "UPSERT_ADMIN_ROLE_QUERY",
    "CountTasksRow",
    "CreateTaskRow",
    "DeleteTaskRow",
    "GetAdminRoleRow",
    "GetTaskRow",
    "ListAdminAuditEventsRow",
    "ListTasksDefaultRow",
    "ListTasksNameAscRow",
    "ListTasksNameDescRow",
    "UpdateTaskRow",
    "count_tasks",
    "create_admin_audit_event",
    "create_task",
    "delete_task",
    "get_admin_role",
    "get_task",
    "list_admin_audit_events",
    "list_tasks_default",
    "list_tasks_name_asc",
    "list_tasks_name_desc",
    "update_task",
    "upsert_admin_role",
]
