"""Secure operational administration for Hayate."""

from .contracts import (
    Actor,
    AdminAction,
    AdminAsset,
    AdminBulkAction,
    AdminField,
    AdminRepository,
    AdminRepositoryFactory,
    AdminResource,
    AdminValidationError,
    AuditEvent,
    AuditHistoryPage,
    AuditHistoryReader,
    AuditHistoryReaderFactory,
    AuditPhase,
    AuditSink,
    AuditSinkFactory,
    Authorizer,
    BulkActionHandler,
    BulkActionResult,
    FieldKind,
    ListQuery,
    Page,
    Record,
)
from .site import AdminSite

__version__ = "0.1.0"

__all__ = [
    "Actor",
    "AdminAction",
    "AdminAsset",
    "AdminBulkAction",
    "AdminField",
    "AdminRepository",
    "AdminRepositoryFactory",
    "AdminResource",
    "AdminSite",
    "AdminValidationError",
    "AuditEvent",
    "AuditHistoryPage",
    "AuditHistoryReader",
    "AuditHistoryReaderFactory",
    "AuditPhase",
    "AuditSink",
    "AuditSinkFactory",
    "Authorizer",
    "BulkActionHandler",
    "BulkActionResult",
    "FieldKind",
    "ListQuery",
    "Page",
    "Record",
    "__version__",
]
